#!/bin/bash

# SPDX-FileCopyrightText: 2021 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause

set -e

branch=$1

if [ -z "$branch" ]; then
    echo "Usage: $0 [branch]"
    exit 1
fi

curdir=$(dirname `readlink -f $0`)

mkdir -p /tmp/build-deps
pushd /tmp/build-deps
git clone git://github.com/liri-infra/ci-scripts
for repo in cmake-shared; do
    ./ci-scripts/build-liri $repo $branch
done
popd
