# SPDX-FileCopyrightText: 2023 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build-archlinux:
    name: Arch Linux
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v5
      - name: Download dependencies
        run: |
          pacman --noconfirm --noprogressbar -Syyu
          pacman --noconfirm --noprogressbar -Sy \
            base-devel \
            doxygen \
            cmake \
            ninja \
            pkgconf \
            qt6-base \
            qt6-declarative \
            qt6-svg \
            qt6-wayland \
            qt6-shadertools \
            wayland-protocols \
            wayland
      - name: Build
        run: |
          cmake -GNinja -B build
          cmake --build build
          cmake --install build
